global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mercurystream'
    static_configs:
      - targets: ['processor:9090']
    metrics_path: /metrics

  - job_name: 'mercurystream-replay'
    static_configs:
      - targets: ['processor-replay:9090']
    metrics_path: /metrics
